package com.techstar.framework.demo.dto;

import com.techstar.framework.service.dto.DictionaryBaseDto;


/**
 *  generated by MyEclipse - Hibernate Tools
 * 
 * @author xcf
 */

public class CompanyDto extends DictionaryBaseDto implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	
	
	

	private String companyName;

	

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	
}