package com.sitechasia.webx.core.dao.hibernate3;

import com.sitechasia.webx.core.model.IDomainObject;
import com.sitechasia.webx.core.model.IValueObjectValidator;

/**
 * Users generated by hbm2java
 */
public class UsersDO implements IDomainObject, IValueObjectValidator {
	private static final long serialVersionUID = 1L;
	// Fields
	private Integer userid;
	private String username;
	private String useremail;

	public String getUseremail() {
		return useremail;
	}

	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	/** default constructor */
	public UsersDO() {
	}

	/** constructor */
	public UsersDO(Integer userid, String username) {
		this.userid = userid;
		this.username = username;
		}

	// Property accessors
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean validate() {
		return true;
	}


}
