package com.techstar.framework.demo.entity;


/**
 *  generated by MyEclipse - Hibernate Tools
 * 
 * @author xcf
 */

public class Company implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	
	
	public String id;

	private String companyName;

	

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	
}