package com.sitechasia.webx.core.utils.populator;

import junit.framework.TestCase;
import java.util.*;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import com.sitechasia.webx.core.utils.populator.WebXTypeConverter;
import com.sitechasia.webx.core.utils.populator.PriTypeConverter;
import com.sitechasia.webx.core.utils.populator.ResultSetBeanPopulator;


/**
 * <p>Title: ResultSetBeanPopulatorTest</p>
 * <p>Description: ResultSetBeanPopulator单元测试类</p>
 *
 * @author mashaojing
 * @version 1.0
 */
public class ResultSetBeanPopulatorTest extends TestCase {
	Connection conn=null;
	Statement statement=null;
	ResultSet rs=null;

	public void setUp() throws Exception{
		super.setUp();
		Class.forName("org.hsqldb.jdbcDriver");
		conn=DriverManager.getConnection("jdbc:hsqldb:.","sa","");
		statement=conn.createStatement();
		statement.executeUpdate("CREATE TABLE book(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,name VARCHAR(256),price INTEGER)");
		statement.executeUpdate("insert into book values(1,'java',25)");
	}

	public void tearDown() throws Exception{
		super.tearDown();
		rs.close();
		statement.close();
		conn.close();
	}

	public void testResultSet2Bean() throws SQLException {
			ResultSetBeanPopulator populator = new ResultSetBeanPopulator();
			WebXTypeConverter converter = new WebXTypeConverter();
			PriTypeConverter priConverter = new PriTypeConverter();
			converter.getConverters().add(priConverter);
			populator.setConverter(converter);

			rs=statement.executeQuery("select * from book ");
            rs.next();

			A beanA = new A();
			Map map = new HashMap();
			populator.populate(rs, beanA, null, null);
			assertEquals(1, beanA.getID());
			assertEquals("java", beanA.getNAME());
			assertEquals(25,beanA.getPRICE());

			populator.populate(rs, map, null, null);
			assertEquals("java", beanA.getNAME());
			assertEquals(25,beanA.getPRICE());
		}

		public class A {
			private int ID;
			private String NAME;
			private int PRICE;
			
			public int getID() {
				return ID;
			}
			public void setId(int id) {
				this.ID = id;
			}
			public String getNAME() {
				return NAME;
			}
			public void setNAME(String name) {
				this.NAME = name;
			}
			public int getPRICE() {
				return PRICE;
			}
			public void setPRICE(int price) {
				PRICE = price;
			}
		}
}



