package com.techstar.framework.service.dto;


/**
 *  generated by MyEclipse - Hibernate Tools
 * 
 * @author xcf
 */

public class DictionaryBaseDto implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	protected String id;  //所有字典表的统一主键

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}